rm client/*.class
rm client/schedule/*.class
rm client/download/*.class
rm client/listener/*.class
rm carrier/*.class
rm tracker/*.class
rm tracker/containers/*.class
rm packets/*.class
rm packets/info/*.class
rm packets/messages/*.class
